export type DataType = {
  id: number;
  title: string;
  name: string;
  firstName: string;
  surName: string;
  city: string;
  team: string;
  age: number;
  food: string;
  color: string;
  score: number;
  rank: number;
  start: string;
  finish: string;
  time: string;
  percent: number;
  done: boolean;
  rating: number;
  relatedTo: number;
  notes: string;
};
